// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZxcmY90qyen-8C_F3tCUsvdXDq6xTbTw',
    appId: '1:426847826706:web:22a82f69fbd229a1b9b9cb',
    messagingSenderId: '426847826706',
    projectId: 'water-pump-90da0',
    authDomain: 'water-pump-90da0.firebaseapp.com',
    storageBucket: 'water-pump-90da0.firebasestorage.app',
    measurementId: 'G-701R7RKZR0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBH8Vjt0TnbKLcTNw62iLvj-Ng1zAzVcc8',
    appId: '1:426847826706:android:689f4ca37a2c1c82b9b9cb',
    messagingSenderId: '426847826706',
    projectId: 'water-pump-90da0',
    storageBucket: 'water-pump-90da0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_oB-w4MEfvXC6RdBVSqPzmnSJQIejzgs',
    appId: '1:426847826706:ios:028f000dc8b4b790b9b9cb',
    messagingSenderId: '426847826706',
    projectId: 'water-pump-90da0',
    storageBucket: 'water-pump-90da0.firebasestorage.app',
    iosBundleId: 'com.example.waterPump',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_oB-w4MEfvXC6RdBVSqPzmnSJQIejzgs',
    appId: '1:426847826706:ios:028f000dc8b4b790b9b9cb',
    messagingSenderId: '426847826706',
    projectId: 'water-pump-90da0',
    storageBucket: 'water-pump-90da0.firebasestorage.app',
    iosBundleId: 'com.example.waterPump',
  );
}
